# Generated by Django 3.2.7 on 2021-12-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_educacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cedula',
            field=models.CharField(max_length=50, unique=True, verbose_name='Cedula'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='perfil',
            field=models.CharField(max_length=50, verbose_name='Perfil'),
        ),
    ]
