# Generated by Django 3.2.7 on 2021-12-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_educacion', '0002_auto_20211211_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='departamento',
            field=models.CharField(max_length=100, verbose_name='Deparatamento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='municipio_de_residencia',
            field=models.CharField(max_length=100, verbose_name='Municipio de Residencia'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='perfil',
            field=models.CharField(max_length=100, verbose_name='Perfil'),
        ),
    ]
